# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/

language: cpp

env:
  global:
  - TCHECKER_BRANCH=master
  - TCHECKER_REPO=${HOME}/tchecker
  - CATCH2_REPO=${HOME}/Catch2

before_cache:
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -mindepth 1 -delete; fi

cache:
  directories:
  - ${HOME}/Library/Caches/Homebrew
  - /usr/local/Homebrew

dist:
- bionic

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc
  - os: osx
    compiler: clang

install:
- . ./ci-scripts/setenv-common.sh
- ./ci-scripts/install-${TRAVIS_OS_NAME}.sh
- . ./ci-scripts/setenv-${TRAVIS_OS_NAME}.sh
- ./ci-scripts/show-config.sh

script:
- ./ci-scripts/build-and-test.sh

addons:
  apt:
    packages:
    - libboost-all-dev
    - valgrind
    - bison
    update: true
  homebrew:
    packages:
    - boost
    - bison@3.4
    update: true

notifications:
  email: true

